/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gv_xem_ds_lop;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import lop.Lop;
import lop.LopDB;
import lop.LopTable;

/**
 *
 * @author tunga
 */
public class DSLopMo extends javax.swing.JFrame {

    /**
     * Creates new form DSLopMo
     */
    int idx;
    LopDB dbLop = new LopDB();
    GiangVienLopDB giangVienLopDB = new GiangVienLopDB();
    ArrayList<Lop> ds;
    public int maGv = 1;
    public DSLopMo() {
        initComponents();
        this.setLocationRelativeTo(null);
        HienThi();
    }
    
    private void HienThi() {
        ds = dbLop.getLop();
        lopTable.setModel(new LopTable(ds));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lopTable = new javax.swing.JTable();
        btnNhanLop = new javax.swing.JButton();
        btnLopCuaToi = new javax.swing.JButton();
        btnHuyNhanLop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách các lớp đang mở");

        lopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lopTable);

        btnNhanLop.setText("Nhận lớp");
        btnNhanLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanLopActionPerformed(evt);
            }
        });

        btnLopCuaToi.setText("Lớp của tôi");

        btnHuyNhanLop.setText("Hủy nhận lớp");
        btnHuyNhanLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyNhanLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNhanLop)
                        .addGap(5, 5, 5)
                        .addComponent(btnHuyNhanLop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLopCuaToi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhanLop)
                    .addComponent(btnLopCuaToi)
                    .addComponent(btnHuyNhanLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanLopActionPerformed
        // TODO add your handling code here:
        String maLop = ds.get(idx).getMa_lop();
        Lop lop = dbLop.getLop(maLop);
        if(lop.getMa_gv() != 0) {
            JOptionPane.showMessageDialog(null, "Lớp này đã có giảng viên dạy", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        if(!giangVienLopDB.checkLichDay(maLop, maGv)) {
            JOptionPane.showMessageDialog(null, "Lớp này trùng lịch với một lớp đã đăng ký dạy", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        dbLop.gvNhanLop(maLop, maGv);
        HienThi();
    }//GEN-LAST:event_btnNhanLopActionPerformed

    private void lopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lopTableMouseClicked
        // TODO add your handling code here:
        idx = lopTable.getSelectedRow();
    }//GEN-LAST:event_lopTableMouseClicked

    private void btnHuyNhanLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyNhanLopActionPerformed
        // TODO add your handling code here:
        String maLop = ds.get(idx).getMa_lop();
        Lop lop = dbLop.getLop(maLop);
        if(lop.getMa_gv() != maGv) {
            JOptionPane.showMessageDialog(null, "Bạn không thể hủy lớp này", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        dbLop.gvHuyLop(maLop);
        HienThi();
    }//GEN-LAST:event_btnHuyNhanLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSLopMo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSLopMo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSLopMo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSLopMo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSLopMo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyNhanLop;
    private javax.swing.JButton btnLopCuaToi;
    private javax.swing.JButton btnNhanLop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lopTable;
    // End of variables declaration//GEN-END:variables
}
