/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinhvien_xem_ds_lop_mo;

import chinh.SinhVien;
import hocphan.HocPhan;
import hocphan.HocPhanDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import lop.Lop;
import lop.LopDB;
import lop.LopTable;

/**
 *
 * @author tunga
 */
public class SinhVienDSLopForm extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private SinhVien sv;
    DangKyHocDB dangKyHocDB = new DangKyHocDB();
    LopDB lopDB = new LopDB();
    HocPhanDB hocPhanDB = new HocPhanDB();
    ArrayList<LopSV> ds;
    int idxLop;

    public SinhVienDSLopForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setSinhVien(SinhVien s) {
        sv = s;
        ds = dangKyHocDB.getLop(s.getMa_nganh());
        for (int i = 0; i < ds.size(); ++i) {
            if (dangKyHocDB.daDangKy(sv.getMa_sv(), ds.get(i).getMa_lop())) {
                ds.get(i).setTrangThai("Đã đăng ký");
            } else {
                ds.get(i).setTrangThai("Chưa đăng ký");
            }
        }
        lopTable.setModel(new LopMoSVTable(ds));
    }

    private void HienThi() {
        ds = dangKyHocDB.getLop(sv.getMa_nganh());
        for (int i = 0; i < ds.size(); ++i) {
            if (dangKyHocDB.daDangKy(sv.getMa_sv(), ds.get(i).getMa_lop())) {
                ds.get(i).setTrangThai("Đã đăng ký");
            } else {
                ds.get(i).setTrangThai("Chưa đăng ký");
            }
        }
        lopTable.setModel(new LopMoSVTable(ds));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lopTable = new javax.swing.JTable();
        btnDangKy = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký học phần");

        lopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lopTable);

        btnDangKy.setText("Đăng ký lớp");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy lớp");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDangKy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKy)
                    .addComponent(btnHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lopTableMouseClicked
        // TODO add your handling code here:
        idxLop = lopTable.getSelectedRow();
    }//GEN-LAST:event_lopTableMouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        try {
            LopSV lop = ds.get(idxLop);
            if (idxLop == -1) {
                throw new IllegalArgumentException("Vui lòng chọn một lớp");
            } else if (!dangKyHocDB.checkTrungLich(sv.getMa_sv(), lop.getTiet_bat_dau(), lop.getTiet_ket_thuc(), lop.getThu())) {
                throw new IllegalArgumentException("Lớp này trùng lịch với một lớp đã đăng ký");
            } else if (lop.getTrangThai() == "Đã đăng ký") {
                throw new IllegalArgumentException("Bạn đã đăng ký lớp này rồi");
            } else if(lop.getSo_luong() >= lop.getSi_so()) {
                throw new IllegalArgumentException("Lớp này đã đầy");
            }
            HocPhan hp = hocPhanDB.getHocPhan(lop.getMa_hp());
            int hocPhi = 300000 * (hp.getTc_lt() + hp.getTc_khac()) + 2 * 300000 * hp.getTc_th();
            if(hocPhi > sv.getTai_khoan()) {
                throw new Exception("Bạn không đủ tiền để đăng ký môn học này");
            }
            dangKyHocDB.dangKyHoc(lop.getMa_lop(), sv.getMa_sv());
            lopDB.updateSL(lop.getMa_lop(), 1);
            HienThi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        LopSV lop = ds.get(idxLop);
        if (idxLop == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn một lớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (lop.getTrangThai() == "Chưa đăng ký") {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa đăng ký môn này", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dangKyHocDB.huyDangKy(lop.getMa_lop(), sv.getMa_sv());
        lopDB.updateSL(lop.getMa_lop(), -1);
        HienThi();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienDSLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienDSLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienDSLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienDSLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SinhVienDSLopForm dialog = new SinhVienDSLopForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnHuy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lopTable;
    // End of variables declaration//GEN-END:variables
}
